//go:build ignore

// Generate the table of OID values
// Run with 'go run gen.go'.
package main

import (
	"bytes"
	"database/sql"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strings"

	_ "github.com/lib/pq"
	"github.com/lib/pq/internal/pqtest"
)

type OID struct {
	ID      int
	Type    string
	Comment string
}

var extra = []OID{
	{0, "", "Not defined by current PostgreSQL (18); kept for compatibility."},
	{210, "smgr", ""},
	{702, "abstime", ""},
	{703, "reltime", ""},
	{704, "tinterval", ""},
	{1023, "_abstime", ""},
	{1024, "_reltime", ""},
	{1025, "_tinterval", ""},
	{2282, "opaque", ""},
}

func main() {
	db, err := sql.Open("postgres", pqtest.DSN(""))
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	var v string
	err = db.QueryRow(`show server_version`).Scan(&v)
	if err != nil {
		log.Fatal(err)
	}
	v, _, _ = strings.Cut(v, " ")

	rows, err := db.Query(`select typname, oid from pg_type where oid < 10000 order by oid`)
	if err != nil {
		log.Fatal(err)
	}

	oids := make([]OID, 0, 256)
	for rows.Next() {
		var oid OID
		err := rows.Scan(&oid.Type, &oid.ID)
		if err != nil {
			log.Fatal(err)
		}
		oids = append(oids, oid)
	}
	if err := rows.Err(); err != nil {
		log.Fatal(err)
	}

	oids = append(oids, extra...)

	var (
		consts = new(bytes.Buffer)
		names  = new(bytes.Buffer)
	)
	fmt.Fprintln(consts, "const (")
	fmt.Fprintln(names, "var TypeName = map[Oid]string{")
	for _, oid := range oids {
		if oid.Comment != "" {
			fmt.Fprintf(consts, "\n// %s\n", oid.Comment)
			fmt.Fprintf(names, "\n// %s\n", oid.Comment)
			continue
		}

		// Special case: this was removed in in 2019 (postgres commit
		// 91595f9d49c) and appearantly unused since 1997. However, ID 210 has
		// since been re-used for _pg_type so we can't add this to the map.
		//
		// Referenced by dolthub/doltgresql: https://github.com/search?q=%22oid.T_smgr%22&type=code
		// May also be referenced in private repos.
		//
		// So still add it as a constant but as alias of T__pg_type. We can't
		// really add it to the map though, but that's okay.
		if oid.Type == "smgr" {
			fmt.Fprintf(consts, "T_%s Oid = T__pg_type\n", oid.Type)
			continue
		}

		fmt.Fprintf(consts, "T_%s Oid = %d\n", oid.Type, oid.ID)
		fmt.Fprintf(names, "T_%s: \"%s\",\n", oid.Type, strings.ToUpper(oid.Type))
	}
	fmt.Fprintln(consts, ")")
	fmt.Fprintln(names, "}")

	head := fmt.Sprintf(
		"// Code generated by gen.go. DO NOT EDIT.\n\n// Last updated for PostgreSQL %s\n\npackage oid\n\n",
		v)
	src, err := format.Source(slices.Concat([]byte(head), consts.Bytes(), names.Bytes()))
	if err != nil {
		log.Fatal(err)
	}
	err = os.WriteFile("types.go", src, 0o666)
	if err != nil {
		log.Fatal(err)
	}
}
